---
- name: Download LazyDocker binary
  get_url:
    url: "https://github.com/jesseduffield/lazydocker/releases/latest/download/lazydocker_Linux_x86_64.tar.gz"
    dest: "/tmp/lazydocker.tar.gz"
    mode: '0644'
  become: false

- name: Create directory for LazyDocker
  file:
    path: /tmp/lazydocker_extracted
    state: directory
  become: false

- name: Unarchive LazyDocker
  unarchive:
    src: "/tmp/lazydocker.tar.gz"
    dest: "/tmp/lazydocker_extracted"
    remote_src: yes
  become: false
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install LazyDocker binary to /usr/local/bin
  copy:
    src: "/tmp/lazydocker_extracted/lazydocker"
    dest: "/usr/local/bin/lazydocker"
    mode: '0755'
    remote_src: yes
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
