---
- name: Install bat
  apt:
    name: bat
    state: present
    update_cache: yes
  become: true

- name: Install btop
  apt:
    name: btop
    state: present
    update_cache: yes
  become: true
