---
- name: Install GNOME Tweaks and Extension Manager
  apt:
    name:
      - gnome-tweaks
      - gnome-shell-extension-manager
      - gnome-shell-extensions
    state: present
    update_cache: yes
  become: true

- name: Install JetBrains Mono font
  apt:
    name: fonts-jetbrains-mono
    state: present
  become: true

- name: Set JetBrains Mono as the default monospace font
  command: gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrains Mono 13'
  become: false
