---
- name: Check if GNOME Tweaks is installed
  command: dpkg -s gnome-tweaks
  register: gnome_tweaks_check
  ignore_errors: true
  changed_when: false
  become: false

- name: Install GNOME Tweaks and Extension Manager
  apt:
    name:
      - gnome-tweaks
      - gnome-shell-extension-manager
      - gnome-shell-extensions
    state: present
    update_cache: yes
  become: true
  when: gnome_tweaks_check.rc != 0

- name: Check if JetBrains Mono font is installed
  command: dpkg -s fonts-jetbrains-mono
  register: font_check
  ignore_errors: true
  changed_when: false
  become: false

- name: Install JetBrains Mono font
  apt:
    name: fonts-jetbrains-mono
    state: present
  become: true
  when: font_check.rc != 0

- name: Set JetBrains Mono as the default monospace font
  command: gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrains Mono 13'
  become: false
