---
- name: Workstation Setup
  hosts: localhost
  become: true
  roles:
    - git
    - google-chrome
    - mongodb-compass
    - docker
    - dbeaver
    - sdkman
    - nvm
    - pnpm
    - harlequin
    - python-uv
    - lazysql
    - antigravity
    - postman
    - gemini-cli
    - github-copilot
    - lazygit
    - lazydocker
    - posting
    - btop
    - bash-config
    - desktop-entries
