---
- name: Workstation Setup
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts as normal user to set ansible_env correctly
      setup:
      become: false
  roles:
    - git
    - google-chrome
    - gnome-setup
    # - mongodb-compass
    - docker
    - dbeaver
    - sdkman
    - nvm
    - pnpm
    - harlequin
    - python-uv
    - php
    - go
    - lazysql
    - ollama
    - antigravity
    - postman
    # - bruno
    - gemini-cli
    - github-copilot
    - lazygit
    - lazydocker
    - posting
    - btop
    - filezilla
    - bash-config
    - desktop-entries
