---
- name: Install dependencies for DBeaver
  apt:
    name:
      - wget
      - gnupg
    state: present

- name: Create directory for DBeaver key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Add DBeaver GPG key
  get_url:
    url: https://dbeaver.io/debs/dbeaver.gpg.key
    dest: /etc/apt/keyrings/dbeaver.asc
    mode: '0644'
  become: true

- name: Add DBeaver repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/dbeaver.asc] https://dbeaver.io/debs/dbeaver-ce /"
    state: present
    filename: dbeaver
  become: true

- name: Install DBeaver Community Edition
  apt:
    name: dbeaver-ce
    state: present
    update_cache: yes
