---
php_extensions:
  - "php-cli"
  - "php-fpm"
  - "php-common"
  - "php-mysql"
  - "php-xml"
  - "php-curl"
  - "php-mbstring"
  - "php-zip"
  - "php-gd"
  - "php-intl"
  - "php-bcmath"
  - "php-sqlite3"
