---
- name: Check if GitHub CLI is installed
  command: "{{ github_cli_package }} --version"
  register: gh_check
  ignore_errors: true
  changed_when: false
  become: false

- name: Install dependencies for GitHub CLI
  apt:
    name:
      - curl
      - gnupg
    state: present
  become: true
  when: gh_check.rc != 0

- name: Create directory for GitHub CLI keyring
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true
  when: gh_check.rc != 0

- name: Add GitHub CLI GPG key
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'
  become: true
  when: gh_check.rc != 0

- name: Add GitHub CLI repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    state: present
    filename: github-cli
  become: true
  when: gh_check.rc != 0

- name: Install GitHub CLI
  apt:
    name: "{{ github_cli_package }}"
    state: present
    update_cache: yes
  become: true
  when: gh_check.rc != 0
