---
- name: Check for Java dependencies
  command: dpkg -s curl zip unzip
  register: sdkman_deps_check
  ignore_errors: true
  changed_when: false
  become: false

- name: Install dependencies for Java
  apt:
    name:
      - curl
      - zip
      - unzip
    state: present
  become: true
  when: sdkman_deps_check.rc != 0

- name: Check if Java (SDKMAN) is installed
  stat:
    path: "{{ ansible_env.HOME }}/.sdkman"
  register: sdkman_stat
  become: false

- name: Download and install Java (via SDKMAN)
  shell: curl -s "https://get.sdkman.io" | bash
  when: not sdkman_stat.stat.exists
  args:
    executable: /bin/bash
  become: false

- name: Ensure Java (SDKMAN) is at the end of bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} JAVA CONFIGURATION"
    insertafter: EOF
    block: |
      #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
      export SDKMAN_DIR="$HOME/.sdkman"
      [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
    state: present
  become: false

