---
tui_apps:
  - name: "LazyDocker"
    exec: "lazydocker"
    icon: "docker"
    comment: "The simple terminal UI for both docker and docker-compose"
  - name: "Btop"
    exec: "btop"
    icon: "utilities-system-monitor"
    comment: "Resource monitor that shows usage and stats"
