---
- name: Check if openclaw is installed
  command: which openclaw
  register: openclaw_check
  ignore_errors: true
  changed_when: false
  become: false

- name: Install Open Claw
  shell: curl -fsSL https://openclaw.ai/install.sh | bash
  args:
    executable: /bin/bash
  when: openclaw_check.rc != 0
  become: false
