---
# Defaults for atuin role
atuin_unmanaged_lines:
  - { file: '.zshrc', line: '. "$HOME/.atuin/bin/env"' }
  - { file: '.zshrc', line: 'eval "$(atuin init zsh)"' }

atuin_shells:
  - { file: '.zshrc', shell: 'zsh' }
