---
- name: Check if Git is installed
  command: git --version
  register: git_check
  ignore_errors: true
  changed_when: false
  become: false

- name: Install Git
  apt:
    name: git
    state: present
  become: true
  when: git_check.rc != 0

- name: Check existing Git User Name
  command: git config --global user.name
  register: existing_git_user
  ignore_errors: true
  changed_when: false
  become: false

- name: Configure Git User Name
  git_config:
    name: user.name
    value: "{{ user_name }}"
    scope: global
  become: false
  when: existing_git_user.stdout == ""

- name: Check existing Git User Email
  command: git config --global user.email
  register: existing_git_email
  ignore_errors: true
  changed_when: false
  become: false

- name: Configure Git User Email
  git_config:
    name: user.email
    value: "{{ user_email }}"
    scope: global
  become: false
  when: existing_git_email.stdout == ""

- name: Create .ssh directory
  file:
    path: ~/.ssh
    state: directory
    mode: "0700"
  become: false

- name: Generate SSH key
  openssh_keypair:
    path: ~/.ssh/id_git
    type: ed25519
    force: false
  become: false

- name: Configure SSH to use id_git for GitHub
  blockinfile:
    path: ~/.ssh/config
    create: yes
    mode: '0600'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - GITHUB"
    block: |
      Host github.com
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_git
  become: false
