---
- name: Install Git
  apt:
    name: git
    state: present
  become: true

- name: Configure Git User Name
  git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global
  become: false

- name: Configure Git User Email
  git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global
  become: false

- name: Create .ssh directory
  file:
    path: ~/.ssh
    state: directory
    mode: "0700"
  become: false

- name: Generate SSH key
  openssh_keypair:
    path: ~/.ssh/id_git
    type: ed25519
    force: false
  become: false
