---
- name: Custom Setup 1
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts as normal user to set ansible_env correctly
      setup:
      become: false
  roles:
    - system
    - google-chrome
    - fonts
    - mongodb-compass
    - docker
    - dbeaver
    - java
    - python
    - go
    - bruno
    - ollama
    - github-copilot
    - opencode
    - lazydocker
    - github-copilot
    - ghostty
