---
- name: Languages configuration for development
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts as normal user to set ansible_env correctly
      setup:
      become: false

    - name: Update apt cache (ignoring unreachable repos)
      shell: apt-get update || true
      become: true
      changed_when: false

  roles:
    - git
    - docker
    - terminal
    - starship
    - neovim
    - java
    - python
    - php
    - go
    - node
    - { role: proverbs, when: install_proverbs | default(false) | bool }
