---
- name: Minimal configuration for get started
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts as normal user to set ansible_env correctly
      setup:
      become: false

    - name: Update apt cache (ignoring unreachable repos)
      shell: apt-get update || true
      become: true
      changed_when: false

  roles:
    - git
    - git-delta
    - docker
    - zsh
    - eza
    - dust
    - starship
    - atuin
    - xh
    - neovim
    - evangelist
    - { role: proverbs, when: install_proverbs | default(false) | bool }
