---
- name: Check for Java dependencies
  command: dpkg -s curl zip unzip
  register: sdkman_deps_check
  ignore_errors: true
  changed_when: false
  become: false

- name: Install dependencies for Java
  apt:
    name:
      - curl
      - zip
      - unzip
    state: present
  become: true
  when: sdkman_deps_check.rc != 0

- name: Check if Java (SDKMAN) is installed
  stat:
    path: "{{ ansible_env.HOME }}/.sdkman"
  register: sdkman_stat
  become: false

- name: Download and install Java (via SDKMAN)
  shell: curl -s "https://get.sdkman.io" | bash
  when: not sdkman_stat.stat.exists
  args:
    executable: /bin/bash
  become: false

- name: Install Java 25
  shell: |
    bash -c "source {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install java {{ java_version }} && sdk default java {{ java_version }}"
  args:
    executable: /bin/bash
  become: false
  register: sdk_output
  changed_when: "'Installing:' in sdk_output.stdout"
