---
- name: Check if NVM is installed
  stat:
    path: "{{ ansible_env.HOME }}/.nvm"
  register: nvm_stat
  become: false

- name: Download and install NVM
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  when: not nvm_stat.stat.exists
  args:
    executable: /bin/bash
  become: false

- name: Ensure NVM is in .zshrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "# {mark} NVM CONFIGURATION"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    state: present
  become: false

- name: Install Node.js 24
  shell: |
    bash -c "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ node_version }} && nvm alias default {{ node_version }}"
  args:
    executable: /bin/bash
  become: false
  register: nvm_output
  changed_when: "'is already installed' not in nvm_output.stdout"

