---
- name: Install LazyDocker binary
  shell: |
    LAZYDOCKER_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazydocker/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
    if [ -z "$LAZYDOCKER_VERSION" ]; then
      echo "Failed to get lazydocker version (API limit?). Retrying with fallback version 0.25.2"
      LAZYDOCKER_VERSION="0.25.2"
    fi
    curl -sLo /tmp/lazydocker.tar.gz "https://github.com/jesseduffield/lazydocker/releases/download/v${LAZYDOCKER_VERSION}/lazydocker_${LAZYDOCKER_VERSION}_Linux_x86_64.tar.gz"
    cd /tmp
    tar xf lazydocker.tar.gz lazydocker
    install lazydocker /usr/local/bin
  args:
    executable: /bin/bash
    creates: /usr/local/bin/lazydocker
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add LazyDocker function wrapper to shell configuration files
  blockinfile:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    marker: "# {mark} LAZYDOCKER ALIASES"
    block: |
      # Intercepta 'docker ps' para executar o lazydocker
      docker() {
          if [ "$1" = "ps" ]; then
              lazydocker
          else
              command docker "$@"
          fi
      }
    state: present
  become: false
  loop:
    - .bashrc
    - .zshrc

