---
- name: Install terminal utilities (bat, btop, jq, zsh)
  apt:
    name:
      - bat
      - btop
      - jq
      - zsh
    state: present
  become: true

# --- ZSH Specific Setup ---

- name: Check if Oh My Zsh is installed
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: oh_my_zsh_stat
  become: false

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  become: false
  when: not oh_my_zsh_stat.stat.exists

- name: Set zsh as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

# --- Shared Configurations (Aliases) ---

- name: Add common aliases to .bashrc and .zshrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    marker: "# {mark} PERSONAL ALIASES"
    block: |
      # Alias para abrir um novo terminal no diretório atual
      alias terminal='{{ terminal_command }} --working-directory="$(pwd)" &'

      # Alias para o bat/cat (no Ubuntu o comando é batcat)
      alias bat='batcat'

      # Alias for installing/updating Genesis
      genesis() {
          curl -sSL https://raw.githubusercontent.com/stanleygomes/genesis/refs/heads/master/bootstrap.sh | bash
      }
    state: present
  become: false
  loop:
    - .bashrc
    - .zshrc

# --- Shell Specific Initializations ---

- name: Add tool initializations to .zshrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "# {mark} TOOL INITIALIZATIONS"
    insertafter: EOF
    block: |
      # Node.js
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

      # PNPM
      export PNPM_HOME="$HOME/.local/share/pnpm"
      case ":$PATH:" in
        *":$PNPM_HOME:"*) ;;
        *) export PATH="$PNPM_HOME:$PATH" ;;
      esac

      # Go
      export PATH=$PATH:$HOME/.local/go/bin:$HOME/go/bin

      # Python
      export PATH="$HOME/.local/bin:$PATH"
  become: false


