---
# List of APT packages to purge
autoremove_apt_packages:
  - firefox
  - filezilla
  - git-delta


# List of Flatpak packages to remove
autoremove_flatpak_packages: []

# List of Snap packages to remove
autoremove_snap_packages: []

# List of desktop shortcut filenames to remove from ~/.local/share/applications/
autoremove_desktop_entries:
  - antigravity-ide.desktop
  - antigravity-url-handler.desktop

# List of custom paths (directories or files) to remove as superuser (become: true)
autoremove_custom_paths:
  - /usr/local/bin/xh
  - /usr/local/bin/lazydocker
  - /usr/share/antigravity-ide
  - /usr/bin/antigravity-ide
  - /usr/bin/antigravity
  - /usr/share/pixmaps/antigravity-ide.png


# List of user-space paths (directories or files) to remove (become: false)
autoremove_user_paths:
  - "{{ ansible_env.HOME }}/.config/nvim"
  - "{{ ansible_env.HOME }}/.local/share/nvim"
  - "{{ ansible_env.HOME }}/.local/state/nvim"
  - "{{ ansible_env.HOME }}/.cache/nvim"
  - "{{ ansible_env.HOME }}/.config/Antigravity IDE"
  - "{{ ansible_env.HOME }}/.antigravity"
