---
- name: AI tools setup
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts as normal user to set ansible_env correctly
      setup:
      become: false

  roles:
    - gemini-cli
    - github-copilot
    - hermes-agent
    - claude-code
    - open-claw
