---
- name: Workstation Setup (Essential)
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts as normal user to set ansible_env correctly
      setup:
      become: false

  roles:
    - git
    - docker
    - sdkman
    - nvm
    - pnpm
    - harlequin
    - python-uv
    - php
    - go
    - gemini-cli
    - github-copilot
    - lazygit
    - lazydocker
    - posting
    - bash-config
    - zsh
