---
- name: Common configuration used for all setups
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts as normal user to set ansible_env correctly
      setup:
      become: false

  roles:
    - system
    - git
    - docker
    - terminal
