---
- name: Workstation Setup (desktop)
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts as normal user to set ansible_env correctly
      setup:
      become: false
  roles:
    - system
    - git
    - google-chrome
    - gnome-setup
    - fonts
    - mongodb-compass
    - docker
    - dbeaver
    - sdkman
    - nvm
    - pnpm
    - python-uv
    - go
    - bruno
    - github-copilot
    - lazygit
    - lazydocker
    - bash-config
    - zsh
