# @sub-options: antigravity, vscode
---
- name: Desktop Setup
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts as normal user to set ansible_env correctly
      setup:
      become: false
  roles:
    - google-chrome
    - gnome-setup
    - fonts
    # - mongodb-compass
    - dbeaver
    - java
    # - harlequin
    - python
    - php
    - go
    # - lazysql
    # - ollama
    - { role: antigravity, when: install_antigravity | default(false) | bool }
    - { role: vscode, when: install_vscode | default(false) | bool }
    - postman
    # - bruno
    - lazygit
    - lazydocker
    - posting
    - filezilla
    - desktop-entries
