---
- name: Workstation Setup (Essential)
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts as normal user to set ansible_env correctly
      setup:
      become: false

  roles:
    - system
    - git
    - docker
    - nvm
    - gemini-cli
    - github-copilot
    - hermes-agent
    - bash-config
    - zsh
