# @sub-options: java, python, php, go, node
- name: Programming Languages Setup
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts as normal user to set ansible_env correctly
      setup:
      become: false
  roles:
    - { role: java, when: install_java | default(true) }
    - { role: python, when: install_python | default(true) }
    - { role: php, when: install_php | default(true) }
    - { role: go, when: install_go | default(true) }
    - { role: node, when: install_node | default(true) }
